In [1]:
import numpy as np
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [2]:
type(a)

numpy.ndarray

In [3]:
import matplotlib as mpl

In [5]:
a = np.array([0, 1, -1, 0] / np.array([1, 0, 0, 0]))

c:\users\ds\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\ds\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [6]:
mpl.show(a)

AttributeError: module 'matplotlib' has no attribute 'show'

In [7]:
c = np.zeros((5,2), dtype='i')

In [8]:
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [9]:
a = np.array([[1,2,3],[4,5,6]], float)
print(a[1,:])
print(a[:,2])
print(a[-1:,-2:])

[4. 5. 6.]
[3. 6.]
[[5. 6.]]


In [10]:
print(a)
print(a.T)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [21]:
a.flatten('q')

TypeError: order not understood

In [18]:
a.ravel('w')

TypeError: order not understood

In [22]:
help(a.flatten)

Help on built-in function flatten:

flatten(...) method of numpy.ndarray instance
    a.flatten(order='C')
    
    Return a copy of the array collapsed into one dimension.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.
    
    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.
    
    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.
    
    Examples
    --------
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3, 2, 4]

In [24]:
help(a.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [39]:
x = np.arange(5)
y = x.reshape(1,5)
z = x[np.newaxis, :]
q = x.flatten()
r = x.ravel()

In [41]:
print(x)
print(y)
print(z)
print(q)
print(r)
x[2] = 99
print(y)
print(z)
print(q)
print(r)

[ 0  1 99  3  4]
[[ 0  1 99  3  4]]
[[ 0  1 99  3  4]]
[0 1 2 3 4]
[ 0  1 99  3  4]
[[ 0  1 99  3  4]]
[[ 0  1 99  3  4]]
[0 1 2 3 4]
[ 0  1 99  3  4]


In [43]:
x = np.arange(3)
y = np.arange(5)
print("x :", x)
print("y :", y)

X, Y = np.meshgrid(x, y)
print("X :", X)
print("Y :", Y)

for i in zip(X, Y):
    print( i )

x : [0 1 2]
y : [0 1 2 3 4]
X : [[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
Y : [[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
(array([0, 1, 2]), array([0, 0, 0]))
(array([0, 1, 2]), array([1, 1, 1]))
(array([0, 1, 2]), array([2, 2, 2]))
(array([0, 1, 2]), array([3, 3, 3]))
(array([0, 1, 2]), array([4, 4, 4]))


In [44]:
a = np.array([1,2,3], int)
b = np.array([4,5,6], int)
a + b

array([5, 7, 9])

In [45]:
a * b

array([ 4, 10, 18])

In [46]:
a * 2

array([2, 4, 6])

In [64]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
print("sum :", a.sum())
print("prod :", a.prod())
print("mean :", a.mean())

sum : 78
prod : 479001600
mean : 6.5


In [69]:
print("sum(axis=0) :", a.sum(axis=0))

sum(axis=0) : [22 26 30]


In [70]:
print("corrcoef() :", np.corrcoef(a))

corrcoef() : [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [72]:
np.histgram(a)

AttributeError: module 'numpy' has no attribute 'histgram'

In [ ]:
dir(a)

In [74]:
a = np.array([1,2,3])
np.dot(a, 3)

array([3, 6, 9])

In [75]:
np.inner(a,3)

array([3, 6, 9])

In [76]:
b = np.array([4,5,6])
np.outer(a,b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [77]:
np.cross(a,b)

array([-3,  6, -3])

In [88]:
b=[4,5,6]
np.dot(a, b, a)

ValueError: output array is not acceptable (must have the right datatype, number of dimensions, and be a C-Array)

In [81]:
a*b

array([ 4, 10, 18])

In [93]:
a = np.array([[0,1], [2,3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
print(repr(np.dot(b, a)))
print(repr(np.dot(a, b)))
print(repr(np.dot(a, c)))
print(repr(np.dot(c, a)))
print(repr(np.matmul(c, a)))
print(repr(c @ a))


array([ 6., 11.])
array([ 3., 13.])
array([[ 4.,  0.],
       [14.,  2.]])
array([[2., 4.],
       [0., 4.]])
array([[2., 4.],
       [0., 4.]])
array([[2., 4.],
       [0., 4.]])


In [3]:
from graphviz import Digraph
dot = Digraph(comment='The Round Table')
dot

ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH

In [2]:
!pip install graphviz

In [95]:
dot.node('A', 'King Arthur')
dot.node('B', 'Sir Bedevere the Wise')
dot.node('L', 'Sir Lancelot the Brave')

dot.edges(['AB', 'AL'])
dot.edge('B', 'L', constraint='false')

NameError: name 'dot' is not defined